# Generated by Django 3.1 on 2020-08-17 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_cultivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cultivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_departamento', models.CharField(max_length=2)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaMunicipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_municipio', models.CharField(max_length=5)),
                ('nombre_municipio', models.CharField(max_length=50)),
                ('id_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.zona')),
            ],
        ),
    ]
